USE [master]
GO
/****** Object:  Database [BDAgenciaTurismo]    Script Date: 16/10/2023 01:20:46 ******/
CREATE DATABASE [BDAgenciaTurismo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bdTurismo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVERDEV2023\MSSQL\DATA\bdTurismo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bdTurismo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVERDEV2023\MSSQL\DATA\bdTurismo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BDAgenciaTurismo] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDAgenciaTurismo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDAgenciaTurismo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDAgenciaTurismo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDAgenciaTurismo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BDAgenciaTurismo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDAgenciaTurismo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET RECOVERY FULL 
GO
ALTER DATABASE [BDAgenciaTurismo] SET  MULTI_USER 
GO
ALTER DATABASE [BDAgenciaTurismo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDAgenciaTurismo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDAgenciaTurismo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDAgenciaTurismo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDAgenciaTurismo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BDAgenciaTurismo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BDAgenciaTurismo', N'ON'
GO
ALTER DATABASE [BDAgenciaTurismo] SET QUERY_STORE = ON
GO
ALTER DATABASE [BDAgenciaTurismo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BDAgenciaTurismo]
GO
/****** Object:  Schema [Cadastro]    Script Date: 16/10/2023 01:20:46 ******/
CREATE SCHEMA [Cadastro]
GO
/****** Object:  Table [Cadastro].[cliente]    Script Date: 16/10/2023 01:20:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Cadastro].[cliente](
	[IdCliente] [int] IDENTITY(1,1) NOT NULL,
	[CPF] [char](11) NOT NULL,
	[nomeCompleto] [varchar](350) NOT NULL,
	[logradouro] [varchar](250) NOT NULL,
	[numero] [smallint] NOT NULL,
	[complemento] [varchar](250) NULL,
	[cep] [char](10) NOT NULL,
	[bairro] [varchar](50) NOT NULL,
	[cidade] [varchar](50) NOT NULL,
	[estado] [varchar](50) NOT NULL,
	[pais] [varchar](50) NOT NULL,
	[telefone] [varchar](20) NOT NULL,
	[email] [nvarchar](100) NOT NULL,
	[senha] [varbinary](12) NOT NULL,
	[DataCadastro] [datetime] NOT NULL,
 CONSTRAINT [PK_cliente] PRIMARY KEY CLUSTERED 
(
	[IdCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Cadastro].[Viagem]    Script Date: 16/10/2023 01:20:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Cadastro].[Viagem](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[IdCliente] [int] NULL,
	[LocalPartida] [varchar](60) NOT NULL,
	[LocalDestino] [varchar](60) NOT NULL,
	[DataPartida] [date] NOT NULL,
	[DataRetorno] [date] NOT NULL,
	[ValorDestino] [float] NOT NULL,
 CONSTRAINT [PK_tb_Viagemp] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Cadastro].[cliente]  WITH CHECK ADD  CONSTRAINT [FK_cliente_cliente] FOREIGN KEY([IdCliente])
REFERENCES [Cadastro].[cliente] ([IdCliente])
GO
ALTER TABLE [Cadastro].[cliente] CHECK CONSTRAINT [FK_cliente_cliente]
GO
ALTER TABLE [Cadastro].[Viagem]  WITH CHECK ADD  CONSTRAINT [FK_tb_Viagem] FOREIGN KEY([IdCliente])
REFERENCES [Cadastro].[cliente] ([IdCliente])
GO
ALTER TABLE [Cadastro].[Viagem] CHECK CONSTRAINT [FK_tb_Viagem]
GO
USE [master]
GO
ALTER DATABASE [BDAgenciaTurismo] SET  READ_WRITE 
GO

